# Using Git

## Philosophy of Git

blah

## Setting up Github + Git for the first time

1. Sign up for a GitHub account
1. Install Git to manage projects locally ([-> install instructions <-](https://git-scm.com/downloads))
1. Configure Git:
  + % `git config --global user.name "Your Name Here"`
  + % `git config --global user.email "your_email@youremail.com"`

## Use case #1: Upload a local project to GitHub

1. Go to your local project folder
```% cd my/local/project/folder```

2. `git init` ; Initialize a git repository from the project folder:

3. `touch Readme.txt` (optional); create a README file in case you are not already using the `cookiecutter` package which already contains a README.md file.

4. `git remote add origin https://github.com/username/myproject.git` ; Connect local repo to GitHub repository


## Git-Specific Commands

`git init`: Initializes a new Git repository. Until you run this command inside a repository or directory, it’s just a regular folder. Only after you input this does it accept further Git commands.

`git config`: Short for “configure,” this is most useful when you’re setting up Git for the first time.

`git help`: Forgot a command? Type this into the command line to bring up the 21 most common git commands. You can also be more specific and type “git help init” or another term to figure out how to use and configure a specific git command.

`git status`: Check the status of your repository. See which files are inside it, which changes still need to be committed, and which branch of the repository you’re currently working on.

`git add`: This does not add new files to your repository. Instead, it brings new files to Git’s attention. After you add files, they’re included in Git’s “snapshots” of the repository.

`git commit`: Git’s most important command. After you make any sort of change, you input this in order to take a “snapshot” of the repository. Usually it goes `git commit -m “Message here.”` The `-m` indicates that the following section of the command should be read as a message.

`git merge`: When you’re done working on a branch, you can merge your changes back to the master branch, which is visible to all collaborators. git merge cats would take all the changes you made to the “cats” branch and add them to the master.

`git push`: If you’re working on your local computer, and want your commits to be visible online on GitHub as well, you “push” the changes up to GitHub with this command.

`git pull`: If you’re working on your local computer and want the most up-to-date version of your repository to work with, you “pull” the changes down from GitHub with this command.
